
# analyzer:
#   exclude: [build/**]
#   language:
#     strict-raw-types: true
#     strict-casts: true
#     strict-inference: true

#   strong-mode:
#     implicit-casts: false

# linter:
#   rules:
#     - cancel_subscriptions
